sudo: required

language: generic

services:
  - docker

before_install:
  - docker-compose build --no-cache
  - docker-compose up

script:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" -- password-stdin

after_success:
  - docker-compose push

#deploy:
#  provider: elasticbeanstalk
#  region: ap-northeast-2
#  app: docker-application
#  env: DockerApplication-env
#  bucket_name: elasticbeanstalk-ap-northeast-2-423124245517
#  bucket_path: docker-application
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY


