version: "3.8"
services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    volumes:
      - ./data/docker:/var/lib/mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_DATABASE: application
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
#    env_file:
#      - ./db_dev.env



  application:
    build:
      context: .
    container_name: application
    volumes:
      - ./data/upload:/static/upload

    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/application
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_ROOT_PASSWORD

#    env_file:
#      - ./db_dev.env
