spring:
  profiles:
    include: db

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    static-path-pattern: /static/**

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace